# ===============================
# DATABASE POSTGESQL
# ===============================

spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/Messenger
        username: postgres
        password: 123

---

# ===============================
# JPA / HIBERNATE
# ===============================

spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect : org.hibernate.dialect.PostgreSQL82Dialect
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

                # Fix Postgres JPA Error:
                # Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.

                temp:
                  use_jdbc_metadata_defaults: false


---

# ===============================
# MONGODB
# ===============================

spring:
    data:
        mongodb:
            uri: mongodb://localhost/Messenger
            port: 27017
            host: localhost

---

# ===============================
# HTTPS
# ===============================

server:
    port: 8443
    ssl.key-store: classpath:keystore.p12
    ssl.key-store-password: 123456
    ssl.keyStoreType: PKCS12
    ssl.keyAlias: tomcat
---

# ===============================
# Limits
# ===============================

spring:
    servlet:
        multipart:
             max-file-size: 128KB
             max-request-size: 128KB